# MakeFile by Klaudiusz

# Find .cpp files in project directory
SRC := $(shell find src -name *.cpp)

CC = g++

LIBPATH = -Llib/SDL2
LINKERFLAGS = -lmingw32 -lSDL2main -lSDL2 -lSDL2_image

INCLUDEPATH = -Iinclude

EXE = bin/tetris

COMPILE = ${INCLUDEPATH} ${LIBPATH} -o ${EXE} ${SRC} ${LINKERFLAGS}

MSG_BEGIN = Compiling project!
MSG_COMPLETED = Compilation completed!

#COPYASSETS = xcopy /E assets\ bin\resources\ 

release:
	@echo ${MSG_BEGIN}
	@echo
	${CC} ${COMPILE}
	@echo
	@echo ${MSG_COMPLETED}

debug:
	@echo ${MSG_BEGIN}
	@echo
	${CC} -g ${COMPILE}
	@echo
	@echo ${MSG_COMPLETED}

test:
	g++ --version
	gcc --version
	gdb --version