# MakeFile by Klaudiusz

# Here add an source files
SRC = src/util/Error.cpp src/graphics/texture/Texture.cpp src/graphics/entity/Entity.cpp src/graphics/entity/Sprite.cpp src/graphics/entity/transform/Transform.cpp src/time/Time.cpp src/module/Window.cpp src/Game.cpp src/main.cpp

CC = g++

LIBPATH = -Llib/SDL2
LINKERFLAGS = -lmingw32 -lSDL2main -lSDL2 -lSDL2_image

INCLUDEPATH = -Iinclude

EXE = bin/tetris

COMPILE = ${INCLUDEPATH} ${LIBPATH} -o ${EXE} ${SRC} ${LINKERFLAGS}

#COPYASSETS = xcopy /E assets\ bin\resources\ 

release:
	$(COPYASSETS)
	${CC} ${COMPILE}

debug:
	$(COPYASSETS)
	${CC} -g ${COMPILE}

test:
	g++ --version
	gcc --version
	gdb --version